// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA2EozQumjiW5KG2iVWA8de4vxSUrgaLyU',
    appId: '1:765459785164:web:3ad2f07b7c9701edbd2969',
    messagingSenderId: '765459785164',
    projectId: 'designsphere-66a0c',
    authDomain: 'designsphere-66a0c.firebaseapp.com',
    storageBucket: 'designsphere-66a0c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1e3eSwqQiYr0ofY71H-s5jn2X2M7qHNE',
    appId: '1:765459785164:android:68ddbf32b5be2bd5bd2969',
    messagingSenderId: '765459785164',
    projectId: 'designsphere-66a0c',
    storageBucket: 'designsphere-66a0c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAKMAwYe0sICQfDkwmE5CH29sb3QrTVKYo',
    appId: '1:765459785164:ios:6800134dc6cef8d9bd2969',
    messagingSenderId: '765459785164',
    projectId: 'designsphere-66a0c',
    storageBucket: 'designsphere-66a0c.firebasestorage.app',
    iosBundleId: 'com.example.designSphere',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAKMAwYe0sICQfDkwmE5CH29sb3QrTVKYo',
    appId: '1:765459785164:ios:6800134dc6cef8d9bd2969',
    messagingSenderId: '765459785164',
    projectId: 'designsphere-66a0c',
    storageBucket: 'designsphere-66a0c.firebasestorage.app',
    iosBundleId: 'com.example.designSphere',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA2EozQumjiW5KG2iVWA8de4vxSUrgaLyU',
    appId: '1:765459785164:web:62b18fd89eaa0d39bd2969',
    messagingSenderId: '765459785164',
    projectId: 'designsphere-66a0c',
    authDomain: 'designsphere-66a0c.firebaseapp.com',
    storageBucket: 'designsphere-66a0c.firebasestorage.app',
  );
}
